### PR TITLE
Added ali_connors

### PR DESCRIPTION
**Pull request by HansMuller**

### CODE REVIEW

**Comment by Hixie** [comment]
That is... not Ali Connors.
Can you confirm the provenance of this image is copyright-sound?

**Comment by Hixie** [comment]
lgtm assuming copyright situation is fine

**Comment by HansMuller** [comment]
The image is just a temporary stand-in until the real Ali Connors shows up

I don't know if the image is copyright-sound.

**Comment by HansMuller** [comment]
I'll substitute this photo: https://commons.wikimedia.org/wiki/File:Curlydisorder.jpg

**Pull request merged**
